[build-system]
requires = ["setuptools>="]
build-backend = "setuptools.build_meta"

[project]
name = "pagure"
version = "2.0.0"
description = "PAGURE is a tool for compiling numerical models and their dependencies."
readme = "README.md"
authors = [
    { name = "Fabien Retif", email = "fabien.retif@snale.net" }
]
license = { text = "MIT" }
requires-python = ">="
dependencies = [
]

[project.urls]
Homepage = "https://lab.snale.net/produits/pagure"
Source = "https://github.com/snale-net/pagure"
